
    <?php error_log($this->title); ?>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?php echo $this->translate('Орфограммы и формулы справочника') ?></h3>
		</div>
		<div class="panel-body">
		<?php foreach ($this->formulas as $formula) : ?>
			<div id="paragraph" >
				<p><span><?php echo $formula['title'];?></span></p>
				<div style="margin-left:15px">
					<?php foreach ($formula['ortho'] as $ortho) : ?>
						<p><span><?php echo $ortho['ortho_name'];?> : </span></p>
						<div style="margin-left:30px">
							<?php foreach ($ortho['formulas'] as $formula) : ?>
								<p><span><?php echo $formula['name'];?> <?php echo $formula['example'];?></span></p>
					    	<?php endforeach; ?>
					    </div>
			    	<?php endforeach; ?>
		    	</div>
			</div>
    	<?php endforeach; ?>
    	</div>
    </div>
    

