<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter45412578 = new Ya.Metrika({
                    id:45412578,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/45412578" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<h4 class="text-center"><?php echo $this->predisl['title'] ?></h4>
<div class="row">
	<div class="col-md-12 text-center">
		<?php echo $this->predisl['sub_title'] ?>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="predisl-empl"><?php echo $this->predisl['empl'] ?></div>
		<div class="predisl"><?php echo $this->predisl['text'] ?></div>
	</div>
	<div class="col-md-1"></div>
</div>