<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter45412578 = new Ya.Metrika({
                    id:45412578,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/45412578" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<h4 class="text-center"><?php echo $this->litra['title'] ?></h4>
<hr>
<div class="row top_buffer">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="predisl-empl text-center"><p><b>НАУЧНАЯ СТАТЬЯ ПО ПРОЕКТУ</b></p></div>
		<div><p><i>Иванова О.Е.</i> <a href= "/doc/ot_orph_slovarya_k_resursu.pdf" target="_blank" rel="noopener noreferrer">От орфографического словаря к электронному орфографическому ресурсу</a></p></div>
	</div>
	<div class="col-md-1"></div>
</div>
<div class="row top_buffer">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="predisl-empl text-center"><?php echo $this->litra['lit_title'] ?></div>
		<div><?php echo $this->litra['lit'] ?></div>
	</div>
	<div class="col-md-1"></div>
</div>
