<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter45412578 = new Ya.Metrika({
                    id:45412578,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/45412578" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<br>
<div><span>На этой странице дан перечень всех <b>орфограмм</b> справочника и относящихся к ним <b>объяснительных формул</b> в соответствии с их принадлежностью к параграфам справочника.</span></div>
<br>
<div><span>При нажатии на ссылку рядом с <b>объяснительной формулой</b> осуществляется поиск статей <b>словаря</b>, указывающих на эту формулу.</span></div>
<br>
<div class="row">
    <div class="col-md-12">    
        <?php echo $this->formulas ?>
	</div>    
</div>
