
<?php
	$wordform = $this->wordform;
	$wordform->setAttribute('action', $this->url('search', array('action' => 'word')));
	$wordform->prepare();
?>
    <div class="row">

	<?php echo $this->form()->openTag($wordform); ?>
	<?php echo $this->formRow($wordform->get('word')); ?>
	<?php echo $this->formSubmit($wordform->get('submit')); ?>
	<?php echo $this->form()->closeTag(); ?>
    </div>
<?php
	$histform = $this->histform;
	$histform->setAttribute('action', $this->url('search', array('action' => 'historic')));
	$histform->prepare();
?>
    <div class="row">

	<?php echo $this->form()->openTag($histform); ?>
	<?php echo $this->formSelect($histform->get('historic')); ?>
	<?php echo $this->formSubmit($histform->get('submithist')); ?>
	<?php echo $this->form()->closeTag(); ?>
    </div>

<?php
	if (isset($this->articles)) {
		echo $this->articles;
	} 
?>
	
<!-- Modal -->
 <div class="modal" id="tutorialModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="modal-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="modal-body">
                <div class="hidden" id="modalStart" > </div>
            </div>
        </div>
    </div>
</div>
