<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter45412578 = new Ya.Metrika({
                    id:45412578,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/45412578" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<?php
	$wordform = $this->wordform;
	$wordform->setAttribute('action', $this->url('search', array('action' => 'word')));
	$wordform->prepare();
?>
	<?php echo $this->form()->openTag($wordform); ?>
		<div class="row">
			<?php echo $this->formRow($wordform->get('word')); ?>
			<?php echo $this->formSubmit($wordform->get('submit')); ?>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="row">
				<?php echo $this->formRow($wordform->get('title_check'), 'append'); ?>
		    	</div>
		    	<div class="row">
				<?php echo $this->formRow($wordform->get('text_check'), 'append'); ?>
				</div>
		    	<div class="row">
				<?php echo $this->formRow($wordform->get('tut_check'), 'append'); ?>
				</div>				
		    	<div class="row">
				<?php echo $this->formRow($wordform->get('yo'), 'append'); ?>
				</div>				
			</div>				
			<div class="col-md-8">
				<div><span>Использование специальных символов в запросе: ? - один любой символ, кроме пробела; * - любая последовательность символов, кроме пробела.</span></div>
				<div><span>Примеры запросов: <b>естеств*</b>, <b>ал?ергия</b>, <b>греч  *th*</b>.</span></div>
			</div>
		</div>
	<?php echo $this->form()->closeTag(); ?>
    
<?php
/*	$histform = $this->histform;
	$histform->setAttribute('action', $this->url('search', array('action' => 'historic')));
	$histform->prepare(); */
?>
<!--    <div class="row"> -->

	<?php //echo $this->form()->openTag($histform); ?>
	<?php //echo $this->formSelect($histform->get('historic')); ?>
	<?php //echo $this->formSubmit($histform->get('submithist')); ?>
	<?php //echo $this->form()->closeTag(); ?>
<!--    </div> -->
	
<?php
/*	if (isset($this->articles)) {
		echo $this->articles;
		if (count($this->articles) > 0) {
			echo $this->paginationControl(
				// the paginator object
				$this->articles,
				// the scrolling style
				'sliding',
				// the partial to use to render the control
				'contents/paginator.phtml',
				// the route to link to when a user clicks a control link
				array('route' => 'search')
 			);
		}
	}*/
?>
	
<!-- Modal -->
 <div class="modal" id="tutorialModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="modal-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="modal-body">
                <div class="hidden" id="modalStart" > </div>
            </div>
        </div>
    </div>
</div>
