        <?php error_log(sprintf("left container %s", $this->leftside)); ?> 
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Содержание') ?></h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <div class="accordion" id="accordion2">
                        <?php foreach ($this->contents as $partname => $part) : ?>
                            <tr>
                                <td>
                                    <div class="accordion-group">
                                        <div class="accordion-heading h5" style="margin-left:15px">
                                            <span><?php echo $this->escapeHtml($partname);?> </span>
                                        </div>
                                    </div>
				    	            <div id=<?php echo ("part".strval($part->id)); ?> class="accordion-body">
                                        <div class="accordion-inner">
                                            <table class="table">
                                                <?php foreach ($part['tiles'] as $tilename => $item) : ?>
                                                    <tr>
                                                        <td>
                                                            <div class="accordion-group">
                                                                <div class="accordion-heading h3" style="margin-left:15px">
                                                                    <a class="accordion-toggle h5" style="text-transform:none" data-toggle="collapse" data-parent="#accordion2" href=<?php echo ("#tile".$item['id']); ?> >
                                                                    <?php echo $this->escapeHtml($tilename);?>
                                                                    </a>    
                                                                </div>
                                                                <div id=<?php echo ("tile".$item['id']); ?> class="accordion-body collapse">
                                                                    <div class="accordion-inner" style="margin-left:15px">
                                                                        <table class="table">
                                                                            <?php foreach ($item['paras'] as $para) : ?>
                                                                                <tr><td>
                                                                                    <a href=<?php echo ("#para".$para['id']); ?> onclick="paraClick(this)" id="<?php echo $para['id']; ?>" ><?php echo $this->escapeHtml($para['name']);?></a><i><?php echo $this->escapeHtml($para['examples']) ?></i>                                                                               
                                                                                </td></tr>
                                                                            <?php endforeach; ?>
                                                                        </table>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </table>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <div>
                </table>        
            </div>
        </div> 
        <script type="text/javascript">
            function paraClick(obj)
            {
                var para = alert($(obj).attr('id'));
                $.ajax({
                    url: 'Application/Controller/IndexController',
//                    async: false,
                    type: 'POST',
                    dataType: "json",
                    data: {
                        ajax : '1',
                        para : para,
             //           token : token,
//                        filename : filename,
                        action : 'viewPara'
                    },
                    success: function(j)
                    {
/*                        var f = '#start';
                        for (var i = 0; i < j.length; i++) {
                            
                    		$(f).after("<div class=\"form-group\" id=\"" + j[i].url + "_form\">\
                            		<div class=\"col-lg-5 field_name\">\
                            			<input type=\"text\" id=\"" + j[i].url + "\" name=\"" + j[i].url + "_name\" value=\"" + j[i].name + "\" />\
                            		</div>\
                                    <div class=\"col-lg-3\">\
                                        <select class=\"field_type\" name=\"" + j[i].url + "_type\" id=\"" + j[i].url + "_type\" onchange=\"changeType(this)\">\
                                            <option value=0 >String</option>\
                                            <option value=1 >Integer</option>\
                                            <option value=2 >Decimal</option>\
                                        </select>\
                                    </div>\
                            		<div class=\"col-lg-2 field_length\">\
                            			<input type=\"text\" id=\"" + j[i].url + "_length\" name=\"" + j[i].url + "_length\" value=\"128\" />\
                            		</div>\
                            	</div>");
                            f = '#' + j[i].url +"_form";
                        }
                        $("button[name='submitAddproduct_types']").prop('disabled', false);
                        var fieldsNames = '';
                		$('.field_name > input').each( function () {
                            if (fieldsNames != '')
                                fieldsNames = fieldsNames + ';';
                            fieldsNames = fieldsNames + $(this).val();                
                		});
                        $('#fields').val(fieldsNames); */
                        
                    },
                    error: function(XMLHttpRequest, textStatus, errorThrown)
                    {
                    }
                });
            }
            
        </script>
