<?php
 // module/Tutorial/view/tutorial/tutorial/index.phtml:

 $title = 'Содержание справочника';
 $this->headTitle($title);
 ?>
 <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Содержание') ?></h3>
            </div>
            <div class="panel-body">
	<!--	<div class="accordion" id="accordion2">
			{foreach name=diag_group from=$diagnoses key=key item=group}
				 	<div class="accordion-group">
					    <div class="accordion-heading h3" style="margin-left:15px">
<!--					      <h4 style="margin-left:15px"> -->
<!--					      <a class="accordion-toggle h4" style="text-transform:none" data-toggle="collapse" data-parent="#accordion2" href="#collapse{$key}">
							{l s=$diagnoses[$key]['group_name']}
      					  </a>
      					  <!-- </h4> -->
<!--    					</div>
				    	<div id="collapse{$key}" class="accordion-body collapse">
				    		<div class="accordion-inner">
								{foreach name=diag from=$group['items'] item=diagnosis}
									<p style="margin-left:30px">
									<a href={$diagnosis['link_rewrite']}>{l s=$diagnosis['name']}</a>
								{/foreach}
	 			     		</div>
    					</div>
    				</div>
    			{/if}
    		{/foreach}
  		</div>
      -->      
                <table class="table">
                    <div class="accordion" id="accordion2">
                        <?php foreach ($content as $key => $part) : ?>
                            <tr>
                                <td>
                                    <div class="accordion-group">
                                        <div class="accordion-heading h5" style="margin-left:15px">
                                            <a class="accordion-toggle h5" style="text-transform:none" data-toggle="collapse" data-parent="#accordion2" href=<?php echo ("#part".$part['id']); ?> >
                                            <?php echo $this->escapeHtml($key);?> 
                                            </a>
                                    </div>
				    	            <div id=<?php echo ("part".$part['id']); ?> class="accordion-body collapse">
                                        <div class="accordion-inner">
                                            <table class="table">
                                                <?php foreach ($part['tiles'] as $key => $item) : ?>
                                                    <tr>
                                                        <td>
                                                            <div class="accordion-group">
                                                                <div class="accordion-heading h3" style="margin-left:15px">
                                                                    <a class="accordion-toggle h5" style="text-transform:none" data-toggle="collapse" data-parent="#accordion2" href=<?php echo ("#tile".$item['id']); ?> >
                                                                    <?php echo $this->escapeHtml($key);?>
                                                                    </a>    
                                                                </div>
                                                                <div id=<?php echo ("tile".$item['id']); ?> class="accordion-body collapse">
                                                                    <div class="accordion-inner" style="margin-left:15px">
                                                                        <table class="table">
                                                                            <?php foreach ($item['paras'] as $para) : ?>
                                                                                <tr><td>
                                                                                    <a href="<?php echo $this->url('paragraph', array('action' => 'view', 'id' => $para['id'])); ?>"><?php echo $this->escapeHtml($para['name']);?></a><i><?php echo $this->escapeHtml($para['examples'])?></i>                                                                               
<!--                                                                                <?php echo $this->escapeHtml($para['name']);?> <i><?php echo $this->escapeHtml($para['examples'])?></i> -->
                                                                                </td></tr>
                                                                            <?php endforeach; ?>
                                                                        </table>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </table>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <div>
                </table>        
<!--            
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p> -->
            </div>
        </div> 
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>

<!-- <h1><?php echo $this->escapeHtml($title); ?></h1> -->
