
    <?php error_log($this->title); ?>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?php echo $this->title; ?></h3>
		</div>
		<div class="panel-body">
			<?php foreach ($this->articles as $article) : ?>
				<div class="row">
					<?php if (count($article['orthos']) > 0 || count($article['paras']) > 0) : ?>
						<div class="col-lg-4" >
							<?php //error_log($article['article']); ?>
							<p><span><?php echo $article['article']; ?></span></p>
						</div>
						<div class="col-lg-8" >
							<div class="accordion" id="accordionOrthos" >
								<?php foreach ($article['orthos'] as $ortho_id => $ortho) : ?>
									<div class="accordion-group" id="accordion-group<?php echo $ortho_id; ?>_<?php echo $article['id']; ?>" >
										<div class="accordion-heading" id="accordion-heading<?php echo $ortho_id; ?>_<?php echo $article['id']; ?>" >
											<a class="accordion-toggle" style="text-transform:none" data-toggle="collapse" data-parent="#accordionOrthos" href="#formulas<?php echo $ortho_id; ?>_<?php echo $article['id']; ?>" ><?php echo $ortho['name'] ?></a >
										</div>
									</div>
									<div id="formulas<?php echo $ortho_id; ?>_<?php echo $article['id']; ?>" class="accordion-body collapse">
										<div class="accordion-inner" id="formulas-inner<?php echo $ortho_id; ?>_<?php echo $article['id']; ?>" style="margin-left:15px">
											<?php foreach ($ortho['formulas'] as $formula) : ?>
												<div><p><a href="<?php echo $this->url('orthogr', array('action' => 'formula', 'id' => $formula['id'])); ?>" ><?php echo $formula['name'] ?></a >
								                <?php if ($formula['example'] != null) echo $formula['example']; ?>
								                <?php if ($formula['rest'] != null) echo $formula['rest']; ?>
												</p></div>
											<?php endforeach; ?>
										</div>
									</div>
								<?php endforeach; ?>
							</div>
							<?php if (count($article['orthos']) > 0) echo "<hr />"; ?>
							<div class="accordion" id="accordionParas" >
								<?php foreach ($article['paras'] as $para_id => $para) : ?>
									<div class="accordion-group" id="accordion-group<?php echo $article['id']; ?>_<?php echo $para_id; ?>" >
										<div class="accordion-heading" id="accordion-heading<?php echo $article['id']; ?>_<?php echo $para_id; ?>" >
											<a class="accordion-toggle" style="text-transform:none" data-toggle="collapse" data-parent="#accordionParas" href="#paras<?php echo $article['id']; ?>_<?php echo $para_id; ?>" >§ <?php echo $para_id ?></a >
										</div>
									</div>
									<div id="paras<?php echo $article['id']; ?>_<?php echo $para_id; ?>" class="accordion-body collapse">
										<div class="accordion-inner" id="paras-inner<?php echo $article['id']; ?>_<?php echo $para_id; ?>" style="margin-left:15px">
											<?php echo $para['title']; ?>
								            <?php foreach ($para['rules'] as $rule) : ?>
												<div><p><?php echo $rule['text']; ?></div></p>
												<div><p><?php echo $rule['info']; ?></div></p>
												<?php if (count($rule['orthos']) > 0) : ?>
													<p><b>Формулы:</b></p>
													<div class="panel panel-default" >
														<div class="panel-body">
															<?php foreach ($rule['orthos'] as $ortho) : ?>
																<div><p><?php echo $ortho['ortho'].": "; ?><?php if ($ortho['formula'] != null) echo "<a href=\"".$this->url('orthogr', array('action' => 'formula', 'id' => $ortho['id_form']))."\" >".$ortho['formula']." </a > " ?><?php if ($ortho['example'] != null) echo $ortho['example']; ?> </p></div>
															<?php endforeach; ?>
														</div>
													</div>
												<?php endif; ?>
											<?php endforeach; ?>
										</div>
									</div>
									<?php foreach ($para['act_rules'] as $act_rule) : ?>
										<?php foreach ($para['rules'] as $rule) : ?>
											<?php if ($rule['id'] == $act_rule) : ?>
												<div class="accordion-group" id="accordion-group<?php echo $article['id']; ?>_<?php echo $act_rule; ?>" >
													<div class="accordion-heading" id="accordion-heading<?php echo $article['id']; ?>_<?php echo $act_rule; ?>" >
														<a class="accordion-toggle" style="text-transform:none" data-toggle="collapse" data-parent="#accordionParas" href="#rules<?php echo $article['id']; ?>_<?php echo $act_rule; ?>" ><?php echo "§ ".$para_id." п. ".$rule['num']; ?></a >
													</div>
												</div>
												<div id="rules<?php echo $article['id']; ?>_<?php echo $act_rule; ?>" class="accordion-body collapse">
													<div class="accordion-inner" id="act_rule-inner<?php echo $article['id']; ?>_<?php echo $act_rule; ?>" style="margin-left:15px">
										            	<?php if (isset($rule['parent'])) : ?>
										            		<?php error_log('parent'); ?>
										            		<div><?php echo $rule['parent']; ?></div>
										            	<?php endif; ?>
													
														<div><p><?php echo $rule['text']; ?></div></p>
														<div><p><?php echo $rule['info']; ?></div></p>
														<?php if (count($rule['orthos']) > 0) : ?>
															<p><b>Формулы:</b></p>
															<div class="panel panel-default" >
																<div class="panel-body">
																	<?php foreach ($rule['orthos'] as $ortho) : ?>
																		<div><p><?php echo $ortho['ortho'].": "; ?><?php if ($ortho['formula'] != null) echo "<a href=\"".$this->url('orthogr', array('action' => 'formula', 'id' => $ortho['id_form']))."\" >".$ortho['formula']." </a > " ?><?php if ($ortho['example'] != null) echo $ortho['example']; ?> </p></div>
																	<?php endforeach; ?>
																</div>
															</div>
														<?php endif; ?>
													</div>
												</div>
												<?php break; ?>
											<?php endif; ?>
										<?php endforeach; ?>
									<?php endforeach; ?>
								<?php endforeach; ?>
							</div>
						</div>
					<?php else: ?>
						<div class="col-lg-12" >
							<?php //error_log($article['article']); ?>
							<p><span><?php echo $article['article']; ?></span></p>
						</div>
					<?php endif; ?>
				</div>
				<?php if (count($articles) > 1) echo "<hr />"; ?>
			<?php endforeach; ?>				
    	</div>
    </div>
