
<?php
	$loginform = $this->loginform;
	$loginform->setAttribute('action', $this->url('adminos', array('action' => 'login')));
	$loginform->prepare();
?>
	<?php echo $this->form()->openTag($loginform); ?>
		<div class="row">
			<?php if ($this->valid == false): ?>
				<div class="alert alert-danger">
			 		Неверный логин и/или пароль.
				</div>			
			<?php endif; ?>	
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-1">
						<?php echo "<span><b>Логин:</b></span>"; ?>
					</div>
					<div class="col-md-2">
						<?php echo $this->formRow($loginform->get('username')); ?>
					</div>
				</div>
				<div class="row top-buffer">
					<div class="col-md-1">
						<?php echo "<span><b>Пароль:</b></span>"; ?>
					</div>
					<div class="col-md-2">
						<?php echo $this->formRow($loginform->get('password')); ?>
					</div>
				</div>
				<div class="row top-buffer">
					<div class="col-md-3 text-right">
						<?php echo $this->formSubmit($loginform->get('submit')); ?>
					</div>
				</div>
			</div>
		</div>
	<?php echo $this->form()->closeTag(); ?>
