<?php
	$wordform = $this->wordform;
	$wordform->setAttribute('action', $this->url('dict', array('action' => 'word')));
	$wordform->prepare();
?>
	<?php echo $this->form()->openTag($wordform); ?>
		<div class="row">
			<div class="col-md-4">
				<div class="row">
					<?php echo $this->formRow($wordform->get('word')); ?>
					<?php echo $this->formSubmit($wordform->get('submit')); ?>
				</div>
				<div class="row">
				<?php echo $this->formRow($wordform->get('title_check'), 'append'); ?>
		    	</div>
		    	<div class="row">
				<?php echo $this->formRow($wordform->get('text_check'), 'append'); ?>
				</div>
			</div>
			<div class="col-md-8">
				<div><span>Использование специальных символов в запросе: ? - один любой символ, кроме пробела; * - любая последовательность символов, кроме пробела.</span></div>
				<div><span>Примеры запросов: <b>естеств*</b>, <b>ал?ергия</b>.</span></div>
			</div>
		</div>
	<?php echo $this->form()->closeTag(); ?>

<?php
		if (isset($this->articles)) {
			echo $this->articles;
		}
?>
<?php
		if (isset($this->article)) {
			echo $this->article;
		}
?>
