<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
<!--                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div> -->
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container" id="main">
            <div row>
                <div class="col-md-4">
                    LEFT COLUMN
<!-- <div class="collapse navbar-collapse"> -->
   <?php echo $this->leftside ?>
    //echo $this->navigation('navigation')
          //    ->menu()
          //    ->setMinDepth(0)
          //    ->setMaxDepth(2)
          //    ->setUlClass('nav navbar-nav');
    ?>
<!-- </div>                    -->
                    <?php //print_r($this->getHelperPluginManager()->getServiceLocator()->get('ContentsMenu')); ?>
                    <?php if ($this->getHelperPluginManager()->getServiceLocator()->get('ContentsMenu') !== null) echo 'ISSET'; ?>
                    <?php //echo $this->partial("contents/contents/left.phtml", array('title' => 'This is title', 'leftside' => $this->getHelperPluginManager()->getServiceLocator()->get('leftside'))); ?>
                    <?php error_log("Hello from layout.phtml");
                          $partial = array('contents/contents/left.phtml', ''); //,  array('leftside' => $this->getHelperPluginManager()->getServiceLocator()->get('navigation'))); 
                          $this->navigation('ContentsMenu')->menu()->setPartial($partial); //, array('leftside' => 
                          //echo $this->getHelperPluginManager()->getServiceLocator()->get('ContentsMenu')->menu();     
                          echo $this->navigation()->menu(); 
                          ?>                    
                    <?php //echo $this->navigation('navigation')->links(); ?>
                    
                    <?php //echo print_r($this->partial); ?> 
                    <?php //echo $this->render('leftside'); ?>
                    <?php //echo $this->leftside; ?>
                </div>
                <div class="col-md-8">
                    <?php echo $this->content; ?>
                </div>
            </div>    
            <hr>
            <footer>
            
                 <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
