
<h4>Информационно-поисковая система</h4>
<h4>разработана при поддержке <a href="http://www.rfh.ru/index.php/ru/">Российского гуманитарного научного фонда</a></h4>
<hr>
<!--<div><span><b>Словарь-справочник</b> состоит из двух частей:</span></div>
<div><span><b>Словаря</b> – расположенных в алфавитном порядке слов с объяснениями при каждом слове и <b>Справочника</b>, содержащего правила правописания, соответствующие объяснительным формулам в словаре.
</span>
</div> 
<br> -->
<div><span><b>Полная по объему словарная статья</b> включает следующие зоны информации:</span></div> 
<div><img src="<?php echo $this->basePath() . '/img/article.png'; ?>"></div>
<!-- Modal -->
 <div class="modal" id="tutorialModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="modal-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="modal-body">
                <div class="hidden" id="modalStart" > </div>
            </div>
        </div>
    </div>
</div>
